"""Initial migration: create all tables

Revision ID: e3ca931a7715
Revises: 
Create Date: 2025-11-13 22:13:21.834854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ca931a7715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_projects',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_projects_id'), 'content_projects', ['id'], unique=False)
    op.create_index(op.f('ix_content_projects_user_id'), 'content_projects', ['user_id'], unique=False)
    op.create_table('content_items',
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('BLOG', 'NEWSLETTER', 'POST', 'SCRIPT', 'IDEA', 'OUTLINE', 'CAMPAIGN', 'HOOK', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_id'), 'content_items', ['id'], unique=False)
    op.create_index(op.f('ix_content_items_project_id'), 'content_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_items_type'), 'content_items', ['type'], unique=False)
    op.create_table('media_files',
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'AUDIO', 'IMAGE', name='mediatype'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_index(op.f('ix_media_files_project_id'), 'media_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_media_files_type'), 'media_files', ['type'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('version_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_versions_item_id'), 'content_versions', ['item_id'], unique=False)
    op.create_table('virality_scores',
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('hook_score', sa.Integer(), nullable=False),
    sa.Column('structure_score', sa.Integer(), nullable=False),
    sa.Column('niche_score', sa.Integer(), nullable=False),
    sa.Column('predicted_engagement', sa.Float(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virality_scores_id'), 'virality_scores', ['id'], unique=False)
    op.create_index(op.f('ix_virality_scores_item_id'), 'virality_scores', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virality_scores_item_id'), table_name='virality_scores')
    op.drop_index(op.f('ix_virality_scores_id'), table_name='virality_scores')
    op.drop_table('virality_scores')
    op.drop_index(op.f('ix_content_versions_item_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_media_files_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_project_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_content_items_type'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_project_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_content_projects_user_id'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_id'), table_name='content_projects')
    op.drop_table('content_projects')
    # ### end Alembic commands ###
